### ISSUE TITLE
Compare menu button should be clickable even if it isn't expanded

### ISSUE THREAD

**Issue by liamdu-popfame** [cuappdev/eatery-blue-ios#137]
If it is a unexpanded circle, it should open compare menu upon click still. If I scroll right now it doesn't open.

**Comment by MrPeterss** [comment]
i made it so you have to scroll down a bit to actually get it to open so that you can't spam open close it by making micro adjustments when scrolling, i can reduce it.

**Comment by MrPeterss** [comment]
it was previously set that users had to scroll 150px up or down to have the opening/closing play. changed it to 40px :)
