### ISSUE TITLE
Filter pill unclickable when editing compare menu dining halls. Also there should be a background gray overlay for the modal pop up.

### ISSUE THREAD

**Issue by liamdu-popfame** [cuappdev/eatery-blue-ios#140]
![image](https://github.com/cuappdev/eatery-blue-ios/assets/159683022/39e967ec-5a18-4fd2-a979-204062cba109)![image](https://github.com/cuappdev/eatery-blue-ios/assets/159683022/577e730b-30b7-44cb-8ce3-a11d975c3e8e)

**Comment by MrPeterss** [comment]
reproducable steps?

**Comment by liamdu-popfame** [comment]
myb. compare any 2 menus through the compare menu button, then click the edit icon top right, then u will see the modal for modifying menus, but u see the pills don't work

**Comment by MrPeterss** [comment]
oops sorry i meant the no gray background part

**Comment by liamdu-popfame** [comment]
same steps

**Comment by MrPeterss** [comment]
all should be fixed now
