### ISSUE TITLE
filtering by BRBs, meal swipes, cash/credit

### ISSUE THREAD

**Issue by matthew-wong8** [cuappdev/eatery-blue-ios#35]
filtering by cash/credit not 100% accurate
- there are eateries in that filtered list that don't have the cash/credit icon
- the cash/credit icon does not show up for some of the eateries

filtering by meal swipes
- why does Morrison dining say "meal swipes allowed" whereas all the other dhalls don't say this
- take out RPCC, it doesn't exist anymore

filtering by BRBs
- becker dining hall says it accepts BRBs but dining halls don't accept BRBs, only meal swipes and cash/credit

**Comment by antoinztte** [comment]
most of these issues seem to be backend/data-related
