### ISSUE TITLE
nearest to you section doesn't display on launch. it takes ~10 sec to load and display.

### ISSUE THREAD

**Issue by matthew-wong8** [cuappdev/eatery-blue-ios#60]

**Comment by antoinztte** [comment]
Are you sure you're on build 26? I'm at Libe rn and just tested the app and my nearest to you is displayed as soon as it launches.

**Comment by matthew-wong8** [comment]
yeah im on build 26. it showed instantly a couple of days ago but not now

**Comment by vinnie4k** [comment]
This is random and depends on the network request.

**Comment by camfruss** [comment]
I was never asked to share my location when downloading the app, so nearest to me didn't show until I manually went into settings.

**Comment by vinnie4k** [comment]
> I was never asked to share my location when downloading the app, so nearest to me didn't show until I manually went into settings.

Most likely because it's an update.

**Comment by vinnie4k** [comment]
Fixed.
