### ISSUE TITLE
View eatery details infinite load glitch

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/eatery-blue-ios#66]
Either viewing eatery details takes extremely long or the details are never loaded (see video):

https://github.com/cuappdev/eatery-blue-ios/assets/22649594/cfa5f322-d0d2-4ffa-8ff2-89a4cd6f10ac

**Comment by vinnie4k** [comment]
This issue can be prevented by filtering. If the filter is selected for "Breakfast", only dining halls with "Breakfast" should display.
