### ISSUE TITLE
Web browser can be closed during log in

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/eatery-blue-ios#69]
After hitting "log in" on the cornell login page in the browser window, it's possible to close the browser window **while** the screen is white and the login details are being populated. Upon closing the browser window I'm taken back to the same login screen, and tapping on the button takes me to the **same** browser session. This could cause undefined behavior if a user closes the window, waits a day, and then hits login again (you'll get a stale request error or some other weird issue). I'd suggest just starting a new session each time the button is clicked.

**Comment by vinnie4k** [comment]
Fixed.
