### ISSUE TITLE
Upon login, loading spinner never stops spinning

### ISSUE THREAD

**Issue by rs929** [cuappdev/eatery-blue-ios#70]
After you login with cornell credentials, the loading spinner continues to spin on the page even when exiting out of the app or switching tabs

<img src = https://github.com/cuappdev/eatery-blue-ios/assets/105038960/2642cd69-e446-4c35-bf58-88f556cd31ef width = "300px" height = "auto">

**Comment by vinnie4k** [comment]
After several hours, I finally figured out the bug. It was due to a race condition. The main thread and a background thread were trying to modify the same resource. Fixed it by making it so one would have to wait for the other.
