### ISSUE TITLE
[UX Request] Favorite eateries

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/eatery-blue-ios#73]
Adding this here as a suggestion: I think having favorite eateries as a horizontal scrolling section under "nearest to you" on the home page would be a much easier modality for accessing favorite eateries. It could also be another tab in the bottom tab navigator maybe.

The current location seems difficult to find, and even though it's in the onboarding it's still annoying to have to go into setting each time to view favorited eateries (presumably the eateries you'd want to see most often). Also the favorites filter on the home page is kind of hard to see.

**Comment by matthew-wong8** [comment]
i believe you can see the favorite eateries on the home screen. you just need to refresh the page after you favorite it. antoinette is working on getting the favorite eatery to automatically display after hitting the favorite button instead of needing to manually refresh

**Comment by vinnie4k** [comment]
> i believe you can see the favorite eateries on the home screen. you just need to refresh the page after you favorite it. antoinette is working on getting the favorite eatery to automatically display after hitting the favorite button instead of needing to manually refresh

Fixed.
