### ISSUE TITLE
Home page filters not working as expected

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/eatery-blue-ios#78]
When I select only cash or credit under payment method, many eateries are displayed that do not accept cash or credit, although the other options seem to work fine. Not sure if this is because no eateries on the app currently accept cash or credit in which case we should still display some sort of message telling the user this.

Steps to reproduce:
1. Open app
2. Tap payment methods filter at top and select cash or credit
3. Scroll to any of displayed eateries and tap it
4. Tap icon in top right of screen and check whether cash or credit is supported

**Comment by vinnie4k** [comment]
Fixed, but it seems like there is a backend issue. 
![image](https://github.com/cuappdev/eatery-blue-ios/assets/75594943/121084ee-eb88-4918-bfbb-daf1d957e3df)
