### ISSUE TITLE
payment methods on home screen doesn’t drop down

### ISSUE THREAD

**Issue by matthew-wong8** [cuappdev/eatery-blue-ios#81]
it's more of a push up from the bottom of the page

**Comment by antoinztte** [comment]
<img width="313" alt="Screenshot 2023-10-13 at 10 44 27 PM" src="https://github.com/cuappdev/eatery-blue-ios/assets/87658310/2e2bb8fd-7134-488c-8e49-80e12c80681a">

This is the design for it. It also matches how we filter breakfast, lunch, and dinner. How do you want us to change it?

**Comment by vinnie4k** [comment]
Looks good to me.

**Comment by antoinztte** [comment]
Fix carrot

**Comment by vinnie4k** [comment]
I don't think this is necessary. The carrot usually indicates that you want to click on it again to reverse the direction (similar to how we do it for upcoming menus).

**Comment by matthew-wong8** [comment]
Ah I see what you mean. Yeah I think it’s fine then
