### ISSUE TITLE
add an interaction that if u swipe right, it returns u to the original upcoming menus page

### ISSUE THREAD

**Issue by matthew-wong8** [cuappdev/eatery-blue-ios#85]
![image](https://github.com/cuappdev/eatery-blue-ios/assets/81109462/2ae69062-21b7-438e-bba6-29baa4a5e5e0)

**Comment by vinnie4k** [comment]
This might be annoying since there are pages here that the user can swipe through. I know that you will have to be closer to the edge in order to dismiss but this may be annoying if the user accidentally dismisses it.
