### ISSUE TITLE
Can we let these sections breathe a little more. Usually it’s not a good idea to ship apps that doesn’t optimize text fitting

### ISSUE THREAD

**Issue by matthew-wong8** [cuappdev/eatery-blue-ios#86]
![image](https://github.com/cuappdev/eatery-blue-ios/assets/81109462/f5ad54f0-fc2f-45e6-a233-a0eda23f6531)
![image](https://github.com/cuappdev/eatery-blue-ios/assets/81109462/8b081c50-db83-4085-ad24-47490700b7b7)

**Comment by vinnie4k** [comment]
This has already been fixed by adding text wrapping.
