### ISSUE TITLE
Incorrect times displayed on homepage

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/eatery-blue-ios#90]
Risley times are displaying incorrectly on homepage (should say closing at 2pm instead of opens at 5pm, observe the "closing in __ minutes" in top right corner)

![image](https://github.com/cuappdev/eatery-blue-ios/assets/22649594/d4ba6d8f-09cf-4f27-8b77-52d4710b8af4)

**Comment by vinnie4k** [comment]
Fixed.
