### ISSUE TITLE
we. should prob redesign how hours are displayed. it looks crammed 

### ISSUE THREAD

**Issue by matthew-wong8** [cuappdev/eatery-blue-ios#97]
![IMG_AAD4A297F18B-1](https://github.com/cuappdev/eatery-blue-ios/assets/81109462/75290ef0-775a-43e4-81a2-e05aaa76fcca)

**Comment by vinnie4k** [comment]
Yes I was going to point this out as well.

**Comment by antoinztte** [comment]
I forgot to create an issue for this but seconded
